version: "3"
services:
  database:
    image: mysql:5.7
    container_name: Vessel
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: docker
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
