// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: vessel.proto

package vesselpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vessel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId   string `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	NaccsCode string `protobuf:"bytes,4,opt,name=naccs_code,json=naccsCode,proto3" json:"naccs_code,omitempty"`
}

func (x *Vessel) Reset() {
	*x = Vessel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vessel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vessel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vessel) ProtoMessage() {}

func (x *Vessel) ProtoReflect() protoreflect.Message {
	mi := &file_vessel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vessel.ProtoReflect.Descriptor instead.
func (*Vessel) Descriptor() ([]byte, []int) {
	return file_vessel_proto_rawDescGZIP(), []int{0}
}

func (x *Vessel) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Vessel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Vessel) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Vessel) GetNaccsCode() string {
	if x != nil {
		return x.NaccsCode
	}
	return ""
}

type Voyage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VesselId          int32                  `protobuf:"varint,2,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	DepartureLocation string                 `protobuf:"bytes,3,opt,name=departure_location,json=departureLocation,proto3" json:"departure_location,omitempty"`
	ArrivalLocation   string                 `protobuf:"bytes,4,opt,name=arrival_location,json=arrivalLocation,proto3" json:"arrival_location,omitempty"`
	DepartureTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=departure_time,json=departureTime,proto3" json:"departure_time,omitempty"`
	ArrivalTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=arrival_time,json=arrivalTime,proto3" json:"arrival_time,omitempty"`
	Details           string                 `protobuf:"bytes,7,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *Voyage) Reset() {
	*x = Voyage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vessel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Voyage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Voyage) ProtoMessage() {}

func (x *Voyage) ProtoReflect() protoreflect.Message {
	mi := &file_vessel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Voyage.ProtoReflect.Descriptor instead.
func (*Voyage) Descriptor() ([]byte, []int) {
	return file_vessel_proto_rawDescGZIP(), []int{1}
}

func (x *Voyage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Voyage) GetVesselId() int32 {
	if x != nil {
		return x.VesselId
	}
	return 0
}

func (x *Voyage) GetDepartureLocation() string {
	if x != nil {
		return x.DepartureLocation
	}
	return ""
}

func (x *Voyage) GetArrivalLocation() string {
	if x != nil {
		return x.ArrivalLocation
	}
	return ""
}

func (x *Voyage) GetDepartureTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartureTime
	}
	return nil
}

func (x *Voyage) GetArrivalTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ArrivalTime
	}
	return nil
}

func (x *Voyage) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

//
//Vessel related messages
type CreateVesselRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vessel *Vessel `protobuf:"bytes,1,opt,name=vessel,proto3" json:"vessel,omitempty"`
}

func (x *CreateVesselRequest) Reset() {
	*x = CreateVesselRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vessel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVesselRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVesselRequest) ProtoMessage() {}

func (x *CreateVesselRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vessel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVesselRequest.ProtoReflect.Descriptor instead.
func (*CreateVesselRequest) Descriptor() ([]byte, []int) {
	return file_vessel_proto_rawDescGZIP(), []int{2}
}

func (x *CreateVesselRequest) GetVessel() *Vessel {
	if x != nil {
		return x.Vessel
	}
	return nil
}

type CreateVesselResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateVesselResponse) Reset() {
	*x = CreateVesselResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vessel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVesselResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVesselResponse) ProtoMessage() {}

func (x *CreateVesselResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vessel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVesselResponse.ProtoReflect.Descriptor instead.
func (*CreateVesselResponse) Descriptor() ([]byte, []int) {
	return file_vessel_proto_rawDescGZIP(), []int{3}
}

func (x *CreateVesselResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetVesselRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetVesselRequest) Reset() {
	*x = GetVesselRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vessel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVesselRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVesselRequest) ProtoMessage() {}

func (x *GetVesselRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vessel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVesselRequest.ProtoReflect.Descriptor instead.
func (*GetVesselRequest) Descriptor() ([]byte, []int) {
	return file_vessel_proto_rawDescGZIP(), []int{4}
}

func (x *GetVesselRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetVesselResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vessel *Vessel `protobuf:"bytes,1,opt,name=vessel,proto3" json:"vessel,omitempty"`
}

func (x *GetVesselResponse) Reset() {
	*x = GetVesselResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vessel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVesselResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVesselResponse) ProtoMessage() {}

func (x *GetVesselResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vessel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVesselResponse.ProtoReflect.Descriptor instead.
func (*GetVesselResponse) Descriptor() ([]byte, []int) {
	return file_vessel_proto_rawDescGZIP(), []int{5}
}

func (x *GetVesselResponse) GetVessel() *Vessel {
	if x != nil {
		return x.Vessel
	}
	return nil
}

type UpdateVesselRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vessel *Vessel `protobuf:"bytes,1,opt,name=vessel,proto3" json:"vessel,omitempty"`
}

func (x *UpdateVesselRequest) Reset() {
	*x = UpdateVesselRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vessel_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVesselRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVesselRequest) ProtoMessage() {}

func (x *UpdateVesselRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vessel_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVesselRequest.ProtoReflect.Descriptor instead.
func (*UpdateVesselRequest) Descriptor() ([]byte, []int) {
	return file_vessel_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateVesselRequest) GetVessel() *Vessel {
	if x != nil {
		return x.Vessel
	}
	return nil
}

type UpdateVesselResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vessel *Vessel `protobuf:"bytes,1,opt,name=vessel,proto3" json:"vessel,omitempty"`
}

func (x *UpdateVesselResponse) Reset() {
	*x = UpdateVesselResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vessel_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVesselResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVesselResponse) ProtoMessage() {}

func (x *UpdateVesselResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vessel_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVesselResponse.ProtoReflect.Descriptor instead.
func (*UpdateVesselResponse) Descriptor() ([]byte, []int) {
	return file_vessel_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateVesselResponse) GetVessel() *Vessel {
	if x != nil {
		return x.Vessel
	}
	return nil
}

type DeleteVesselRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteVesselRequest) Reset() {
	*x = DeleteVesselRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vessel_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVesselRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVesselRequest) ProtoMessage() {}

func (x *DeleteVesselRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vessel_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVesselRequest.ProtoReflect.Descriptor instead.
func (*DeleteVesselRequest) Descriptor() ([]byte, []int) {
	return file_vessel_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteVesselRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteVesselResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DeleteVesselResponse) Reset() {
	*x = DeleteVesselResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vessel_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVesselResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVesselResponse) ProtoMessage() {}

func (x *DeleteVesselResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vessel_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVesselResponse.ProtoReflect.Descriptor instead.
func (*DeleteVesselResponse) Descriptor() ([]byte, []int) {
	return file_vessel_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteVesselResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type GetVesselsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetVesselsRequest) Reset() {
	*x = GetVesselsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vessel_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVesselsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVesselsRequest) ProtoMessage() {}

func (x *GetVesselsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vessel_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVesselsRequest.ProtoReflect.Descriptor instead.
func (*GetVesselsRequest) Descriptor() ([]byte, []int) {
	return file_vessel_proto_rawDescGZIP(), []int{10}
}

type GetVesselsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vessels []*Vessel `protobuf:"bytes,1,rep,name=vessels,proto3" json:"vessels,omitempty"`
}

func (x *GetVesselsResponse) Reset() {
	*x = GetVesselsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vessel_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVesselsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVesselsResponse) ProtoMessage() {}

func (x *GetVesselsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vessel_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVesselsResponse.ProtoReflect.Descriptor instead.
func (*GetVesselsResponse) Descriptor() ([]byte, []int) {
	return file_vessel_proto_rawDescGZIP(), []int{11}
}

func (x *GetVesselsResponse) GetVessels() []*Vessel {
	if x != nil {
		return x.Vessels
	}
	return nil
}

type CreateVoyageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Voyage *Voyage `protobuf:"bytes,1,opt,name=voyage,proto3" json:"voyage,omitempty"`
}

func (x *CreateVoyageRequest) Reset() {
	*x = CreateVoyageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vessel_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVoyageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVoyageRequest) ProtoMessage() {}

func (x *CreateVoyageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vessel_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVoyageRequest.ProtoReflect.Descriptor instead.
func (*CreateVoyageRequest) Descriptor() ([]byte, []int) {
	return file_vessel_proto_rawDescGZIP(), []int{12}
}

func (x *CreateVoyageRequest) GetVoyage() *Voyage {
	if x != nil {
		return x.Voyage
	}
	return nil
}

type CreateVoyageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateVoyageResponse) Reset() {
	*x = CreateVoyageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vessel_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVoyageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVoyageResponse) ProtoMessage() {}

func (x *CreateVoyageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vessel_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVoyageResponse.ProtoReflect.Descriptor instead.
func (*CreateVoyageResponse) Descriptor() ([]byte, []int) {
	return file_vessel_proto_rawDescGZIP(), []int{13}
}

func (x *CreateVoyageResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetVoyageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VoyageId int32 `protobuf:"varint,1,opt,name=voyage_id,json=voyageId,proto3" json:"voyage_id,omitempty"`
	VesselId int32 `protobuf:"varint,2,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
}

func (x *GetVoyageRequest) Reset() {
	*x = GetVoyageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vessel_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVoyageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVoyageRequest) ProtoMessage() {}

func (x *GetVoyageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vessel_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVoyageRequest.ProtoReflect.Descriptor instead.
func (*GetVoyageRequest) Descriptor() ([]byte, []int) {
	return file_vessel_proto_rawDescGZIP(), []int{14}
}

func (x *GetVoyageRequest) GetVoyageId() int32 {
	if x != nil {
		return x.VoyageId
	}
	return 0
}

func (x *GetVoyageRequest) GetVesselId() int32 {
	if x != nil {
		return x.VesselId
	}
	return 0
}

type GetVoyageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Voyage *Voyage `protobuf:"bytes,1,opt,name=voyage,proto3" json:"voyage,omitempty"`
}

func (x *GetVoyageResponse) Reset() {
	*x = GetVoyageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vessel_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVoyageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVoyageResponse) ProtoMessage() {}

func (x *GetVoyageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vessel_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVoyageResponse.ProtoReflect.Descriptor instead.
func (*GetVoyageResponse) Descriptor() ([]byte, []int) {
	return file_vessel_proto_rawDescGZIP(), []int{15}
}

func (x *GetVoyageResponse) GetVoyage() *Voyage {
	if x != nil {
		return x.Voyage
	}
	return nil
}

type UpdateVoyageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Voyage *Voyage `protobuf:"bytes,1,opt,name=voyage,proto3" json:"voyage,omitempty"`
}

func (x *UpdateVoyageRequest) Reset() {
	*x = UpdateVoyageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vessel_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVoyageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVoyageRequest) ProtoMessage() {}

func (x *UpdateVoyageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vessel_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVoyageRequest.ProtoReflect.Descriptor instead.
func (*UpdateVoyageRequest) Descriptor() ([]byte, []int) {
	return file_vessel_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateVoyageRequest) GetVoyage() *Voyage {
	if x != nil {
		return x.Voyage
	}
	return nil
}

type UpdateVoyageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Voyage *Voyage `protobuf:"bytes,1,opt,name=voyage,proto3" json:"voyage,omitempty"`
}

func (x *UpdateVoyageResponse) Reset() {
	*x = UpdateVoyageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vessel_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVoyageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVoyageResponse) ProtoMessage() {}

func (x *UpdateVoyageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vessel_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVoyageResponse.ProtoReflect.Descriptor instead.
func (*UpdateVoyageResponse) Descriptor() ([]byte, []int) {
	return file_vessel_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateVoyageResponse) GetVoyage() *Voyage {
	if x != nil {
		return x.Voyage
	}
	return nil
}

var File_vessel_proto protoreflect.FileDescriptor

var file_vessel_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x76, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x63, 0x6d, 0x64, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a, 0x06, 0x56, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x6e, 0x61, 0x63, 0x63, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6e, 0x61, 0x63, 0x63, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x22, 0xab, 0x02, 0x0a,
	0x06, 0x56, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x65, 0x73, 0x73, 0x65,
	0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x76, 0x65, 0x73, 0x73,
	0x65, 0x6c, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x12, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72,
	0x65, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x11, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x5f, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61,
	0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x41,
	0x0a, 0x0e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0d, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0b, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x3a, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x23, 0x0a, 0x06, 0x76, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x56, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x52, 0x06,
	0x76, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x22, 0x26, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x56, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x22,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x56, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x38, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x56, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x06, 0x76, 0x65, 0x73, 0x73, 0x65,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x56, 0x65,
	0x73, 0x73, 0x65, 0x6c, 0x52, 0x06, 0x76, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x22, 0x3a, 0x0a, 0x13,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x06, 0x76, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x56, 0x65, 0x73, 0x73, 0x65, 0x6c,
	0x52, 0x06, 0x76, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x22, 0x3b, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x56, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x23, 0x0a, 0x06, 0x76, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x56, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x52, 0x06, 0x76,
	0x65, 0x73, 0x73, 0x65, 0x6c, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56,
	0x65, 0x73, 0x73, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x14,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x13, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x56, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x3b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x56, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x07, 0x76, 0x65, 0x73, 0x73, 0x65,
	0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x56,
	0x65, 0x73, 0x73, 0x65, 0x6c, 0x52, 0x07, 0x76, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x73, 0x22, 0x3a,
	0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x06, 0x76, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x56, 0x6f, 0x79, 0x61,
	0x67, 0x65, 0x52, 0x06, 0x76, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x22, 0x26, 0x0a, 0x14, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x56, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x4c, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x56, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x6f, 0x79, 0x61, 0x67, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x76, 0x6f, 0x79, 0x61, 0x67,
	0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x76, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x49, 0x64,
	0x22, 0x38, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x56, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x06, 0x76, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x56, 0x6f, 0x79, 0x61,
	0x67, 0x65, 0x52, 0x06, 0x76, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x22, 0x3a, 0x0a, 0x13, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x56, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x23, 0x0a, 0x06, 0x76, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x56, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x52, 0x06,
	0x76, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x22, 0x3b, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x56, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23,
	0x0a, 0x06, 0x76, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x56, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x52, 0x06, 0x76, 0x6f, 0x79,
	0x61, 0x67, 0x65, 0x32, 0xe8, 0x03, 0x0a, 0x0d, 0x56, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56,
	0x65, 0x73, 0x73, 0x65, 0x6c, 0x12, 0x18, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x56, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x73, 0x73,
	0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x56, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x73, 0x12, 0x16, 0x2e, 0x63, 0x6d, 0x64,
	0x2e, 0x47, 0x65, 0x74, 0x56, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x65, 0x73, 0x73,
	0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a,
	0x09, 0x47, 0x65, 0x74, 0x56, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x12, 0x15, 0x2e, 0x63, 0x6d, 0x64,
	0x2e, 0x47, 0x65, 0x74, 0x56, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x65, 0x73, 0x73, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x12, 0x18, 0x2e, 0x63, 0x6d,
	0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x56, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x45, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x6f, 0x79, 0x61,
	0x67, 0x65, 0x12, 0x18, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56,
	0x6f, 0x79, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x63,
	0x6d, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x09, 0x47, 0x65, 0x74,
	0x56, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x12, 0x15, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x47, 0x65, 0x74,
	0x56, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x63, 0x6d, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x56, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x12, 0x18, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x56, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x6f,
	0x79, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0e,
	0x5a, 0x0c, 0x63, 0x6d, 0x64, 0x2f, 0x76, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vessel_proto_rawDescOnce sync.Once
	file_vessel_proto_rawDescData = file_vessel_proto_rawDesc
)

func file_vessel_proto_rawDescGZIP() []byte {
	file_vessel_proto_rawDescOnce.Do(func() {
		file_vessel_proto_rawDescData = protoimpl.X.CompressGZIP(file_vessel_proto_rawDescData)
	})
	return file_vessel_proto_rawDescData
}

var file_vessel_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_vessel_proto_goTypes = []interface{}{
	(*Vessel)(nil),                // 0: cmd.Vessel
	(*Voyage)(nil),                // 1: cmd.Voyage
	(*CreateVesselRequest)(nil),   // 2: cmd.CreateVesselRequest
	(*CreateVesselResponse)(nil),  // 3: cmd.CreateVesselResponse
	(*GetVesselRequest)(nil),      // 4: cmd.GetVesselRequest
	(*GetVesselResponse)(nil),     // 5: cmd.GetVesselResponse
	(*UpdateVesselRequest)(nil),   // 6: cmd.UpdateVesselRequest
	(*UpdateVesselResponse)(nil),  // 7: cmd.UpdateVesselResponse
	(*DeleteVesselRequest)(nil),   // 8: cmd.DeleteVesselRequest
	(*DeleteVesselResponse)(nil),  // 9: cmd.DeleteVesselResponse
	(*GetVesselsRequest)(nil),     // 10: cmd.GetVesselsRequest
	(*GetVesselsResponse)(nil),    // 11: cmd.GetVesselsResponse
	(*CreateVoyageRequest)(nil),   // 12: cmd.CreateVoyageRequest
	(*CreateVoyageResponse)(nil),  // 13: cmd.CreateVoyageResponse
	(*GetVoyageRequest)(nil),      // 14: cmd.GetVoyageRequest
	(*GetVoyageResponse)(nil),     // 15: cmd.GetVoyageResponse
	(*UpdateVoyageRequest)(nil),   // 16: cmd.UpdateVoyageRequest
	(*UpdateVoyageResponse)(nil),  // 17: cmd.UpdateVoyageResponse
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
}
var file_vessel_proto_depIdxs = []int32{
	18, // 0: cmd.Voyage.departure_time:type_name -> google.protobuf.Timestamp
	18, // 1: cmd.Voyage.arrival_time:type_name -> google.protobuf.Timestamp
	0,  // 2: cmd.CreateVesselRequest.vessel:type_name -> cmd.Vessel
	0,  // 3: cmd.GetVesselResponse.vessel:type_name -> cmd.Vessel
	0,  // 4: cmd.UpdateVesselRequest.vessel:type_name -> cmd.Vessel
	0,  // 5: cmd.UpdateVesselResponse.vessel:type_name -> cmd.Vessel
	0,  // 6: cmd.GetVesselsResponse.vessels:type_name -> cmd.Vessel
	1,  // 7: cmd.CreateVoyageRequest.voyage:type_name -> cmd.Voyage
	1,  // 8: cmd.GetVoyageResponse.voyage:type_name -> cmd.Voyage
	1,  // 9: cmd.UpdateVoyageRequest.voyage:type_name -> cmd.Voyage
	1,  // 10: cmd.UpdateVoyageResponse.voyage:type_name -> cmd.Voyage
	2,  // 11: cmd.VesselService.CreateVessel:input_type -> cmd.CreateVesselRequest
	10, // 12: cmd.VesselService.GetVessels:input_type -> cmd.GetVesselsRequest
	4,  // 13: cmd.VesselService.GetVessel:input_type -> cmd.GetVesselRequest
	6,  // 14: cmd.VesselService.UpdateVessel:input_type -> cmd.UpdateVesselRequest
	12, // 15: cmd.VesselService.CreateVoyage:input_type -> cmd.CreateVoyageRequest
	14, // 16: cmd.VesselService.GetVoyage:input_type -> cmd.GetVoyageRequest
	16, // 17: cmd.VesselService.UpdateVoyage:input_type -> cmd.UpdateVoyageRequest
	3,  // 18: cmd.VesselService.CreateVessel:output_type -> cmd.CreateVesselResponse
	11, // 19: cmd.VesselService.GetVessels:output_type -> cmd.GetVesselsResponse
	5,  // 20: cmd.VesselService.GetVessel:output_type -> cmd.GetVesselResponse
	7,  // 21: cmd.VesselService.UpdateVessel:output_type -> cmd.UpdateVesselResponse
	13, // 22: cmd.VesselService.CreateVoyage:output_type -> cmd.CreateVoyageResponse
	15, // 23: cmd.VesselService.GetVoyage:output_type -> cmd.GetVoyageResponse
	17, // 24: cmd.VesselService.UpdateVoyage:output_type -> cmd.UpdateVoyageResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_vessel_proto_init() }
func file_vessel_proto_init() {
	if File_vessel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vessel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vessel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vessel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Voyage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vessel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVesselRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vessel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVesselResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vessel_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVesselRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vessel_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVesselResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vessel_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVesselRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vessel_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVesselResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vessel_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteVesselRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vessel_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteVesselResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vessel_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVesselsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vessel_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVesselsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vessel_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVoyageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vessel_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVoyageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vessel_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVoyageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vessel_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVoyageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vessel_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVoyageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vessel_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVoyageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vessel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vessel_proto_goTypes,
		DependencyIndexes: file_vessel_proto_depIdxs,
		MessageInfos:      file_vessel_proto_msgTypes,
	}.Build()
	File_vessel_proto = out.File
	file_vessel_proto_rawDesc = nil
	file_vessel_proto_goTypes = nil
	file_vessel_proto_depIdxs = nil
}
