// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	model "github.com/97vaibhav/Vessel_tracking/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// VesselUsecase is an autogenerated mock type for the VesselUsecase type
type VesselUsecase struct {
	mock.Mock
}

// CreateVessel provides a mock function with given fields: vessel
func (_m *VesselUsecase) CreateVessel(vessel *model.Vessel) (*model.Vessel, error) {
	ret := _m.Called(vessel)

	var r0 *model.Vessel
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Vessel) (*model.Vessel, error)); ok {
		return rf(vessel)
	}
	if rf, ok := ret.Get(0).(func(*model.Vessel) *model.Vessel); ok {
		r0 = rf(vessel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Vessel)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Vessel) error); ok {
		r1 = rf(vessel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateVoyage provides a mock function with given fields: voyage
func (_m *VesselUsecase) CreateVoyage(voyage *model.Voyage) (*model.Voyage, error) {
	ret := _m.Called(voyage)

	var r0 *model.Voyage
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Voyage) (*model.Voyage, error)); ok {
		return rf(voyage)
	}
	if rf, ok := ret.Get(0).(func(*model.Voyage) *model.Voyage); ok {
		r0 = rf(voyage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Voyage)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Voyage) error); ok {
		r1 = rf(voyage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVessel provides a mock function with given fields: _a0
func (_m *VesselUsecase) GetVessel(_a0 model.VesselID) (*model.Vessel, error) {
	ret := _m.Called(_a0)

	var r0 *model.Vessel
	var r1 error
	if rf, ok := ret.Get(0).(func(model.VesselID) (*model.Vessel, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(model.VesselID) *model.Vessel); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Vessel)
		}
	}

	if rf, ok := ret.Get(1).(func(model.VesselID) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVessels provides a mock function with given fields:
func (_m *VesselUsecase) GetVessels() ([]*model.Vessel, error) {
	ret := _m.Called()

	var r0 []*model.Vessel
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*model.Vessel, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*model.Vessel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Vessel)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVoyage provides a mock function with given fields: voyageId, vesselId
func (_m *VesselUsecase) GetVoyage(voyageId model.VoyageID, vesselId model.VesselID) (*model.Voyage, error) {
	ret := _m.Called(voyageId, vesselId)

	var r0 *model.Voyage
	var r1 error
	if rf, ok := ret.Get(0).(func(model.VoyageID, model.VesselID) (*model.Voyage, error)); ok {
		return rf(voyageId, vesselId)
	}
	if rf, ok := ret.Get(0).(func(model.VoyageID, model.VesselID) *model.Voyage); ok {
		r0 = rf(voyageId, vesselId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Voyage)
		}
	}

	if rf, ok := ret.Get(1).(func(model.VoyageID, model.VesselID) error); ok {
		r1 = rf(voyageId, vesselId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateVessel provides a mock function with given fields: vessel
func (_m *VesselUsecase) UpdateVessel(vessel *model.Vessel) (*model.Vessel, error) {
	ret := _m.Called(vessel)

	var r0 *model.Vessel
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Vessel) (*model.Vessel, error)); ok {
		return rf(vessel)
	}
	if rf, ok := ret.Get(0).(func(*model.Vessel) *model.Vessel); ok {
		r0 = rf(vessel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Vessel)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Vessel) error); ok {
		r1 = rf(vessel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateVoyage provides a mock function with given fields: voyage
func (_m *VesselUsecase) UpdateVoyage(voyage *model.Voyage) (*model.Voyage, error) {
	ret := _m.Called(voyage)

	var r0 *model.Voyage
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Voyage) (*model.Voyage, error)); ok {
		return rf(voyage)
	}
	if rf, ok := ret.Get(0).(func(*model.Voyage) *model.Voyage); ok {
		r0 = rf(voyage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Voyage)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Voyage) error); ok {
		r1 = rf(voyage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewVesselUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewVesselUsecase creates a new instance of VesselUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewVesselUsecase(t mockConstructorTestingTNewVesselUsecase) *VesselUsecase {
	mock := &VesselUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
